### ISSUE TITLE
Function calls from element onclick results in error

### ISSUE THREAD

**Issue by CyrilSLi** [brython-dev/brython#2254]
Code:
```python
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
</head>
<body onload="brython ()">
    <script type="text/python">
        from browser import document, html, window
        def foo ():
           print ("bar")
        window.foo = foo
        document <= html.BUTTON ("Foo", type = "button", onclick = "foo ();")
    </script>
</body>
</html>
```
Expected behaviour: "bar" is printed when "Foo" button is clicked
Behaviour on Brython 3.11.0: Same as expected
Behaviour on Brython 3.11.1 and later: Raises `TypeError: f is not a function` and does not run the function

Tested on macOS Ventura 13.1 with Chrome 117 and Safari 16.2

**Comment by denis-migdal** [comment]
Hi,

I think you are using it wrong. The following code is working :
```html
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
</head>
<body onload="brython ()">
    <script type="text/python">
        from browser import document, html, window
        def foo (ev):
           print ("bar")
        window.foo = foo
        document <= html.BUTTON ("Foo", type = "button", onclick = foo)
    </script>
</body>
</html>
```

**Comment by denis-migdal** [comment]
@PierreQuentel We have an issue I think :

```python
        from browser import document, html
        def foo (ev):
           print ("bor")
        def faa (ev):
           print ("bar")
        def fuu (ev):
           print ("bur")

        btn = html.BUTTON ("Foo", type = "button", onclick = foo)
        document <= btn

        btn.onclick = faa
        btn.onclick = fuu

        print(btn.onclick)
```

Gives :
```
None
bor
bar
bur
```

Which is *very* confusing. We would expect that `onclick=` would *_replace_* the current listener by a new one.

**_Proposed solution :_**

- let `.onclick` returns the list of listeners
- use `.onclick <= foo` to _**add**_ a new listener.
- keep `.onclick = foo` for backward compatibility ?

**Comment by denis-migdal** [comment]
Another bug (I think linked to #2249 ):

A new wrapper is called at each demand, hence listener create through `onclick = window.foo` is not recognized by `unbind('click, window.foo)`.
Using `WeakMap` and `WeakRef` to cache wrapper once create (and kept alive as long as the target stays alive) would solve this issue. 

```html
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
</head>
<body onload="brython ()">
    <script type="text/javascript">
        window.foo = ev => console.log('foo')
    </script>
    <script type="text/python">
        from browser import document, html, window

        btn = html.BUTTON ("Foo", type = "button", onclick=window.foo)
        document <= btn

        btn.unbind('click', window.foo)
    </script>
</body>
</html>
```

Gives :
```
Traceback (most recent call last):
  File "http://localhost:3000/test.html#__main__", line 6, in <module>
    btn.unbind('click', window.foo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function is not an event callback brython.min.js:1:749467
```

Same with :
```html
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
</head>
<body onload="brython ()">
    <script type="text/javascript">
        //window.foo = ev => console.log('foo')
    </script>
    <script type="text/python">
        from browser import document, html, window

        def foo(ev):
            print('foo')

        window.foo = foo

        btn = html.BUTTON ("Foo", type = "button", onclick=window.foo)
        document <= btn

        btn.unbind('click', window.foo)
    </script>
</body>
</html>
```

**Comment by CyrilSLi** [comment]
> Hi,
> 
> The following code is working :
> 
> ```
> <html lang="en">
> <head>
>     <meta charset="utf-8">
>     <script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
> </head>
> <body onload="brython ()">
>     <script type="text/python">
>         from browser import document, html
>         def foo (ev):
>            print ("bar")
>         document <= html.BUTTON ("Foo", type = "button", onclick = foo)
>     </script>
> </body>
> </html>
> ```
> 
> **_EDIT:_** I seems `onclick` is implemented using `bind()` ? Indeed, it seems we can remove the listener by using `unbind()` later.
> 
> That would explain why it doesn't accept a `str` (and in my mind shouldn't accept a `str`).
> 
> **_Note :_** In JS it is often considered unsafe to use `onXXXX` and is often preferred to use `addEventListener()` (`bind()` in Brython).
> 
> Indeed, the listener you add through `onclick` and be removed by other code trying to add their own listener through `onclick`. Using `addEventListener()` (`bind()` in Brython) enables to register many listeners (not just one), you can later remove with `removeEventListener()` (`unbind()` in Brython).
> 
> Imma test some stuff ^^.

So is binding a string to onclick unintended behaviour? It seems to work from 3.4 to 3.11.0.

**Comment by denis-migdal** [comment]
> So is binding a string to onclick unintended behaviour? It seems to work from 3.4 to 3.11.0.
I don't know.
 
> **Edit:** it is really easy to call a function with arguments if you bind a string (`onclick = "foo (True);"`), how would I do that if I bind a function object? Binding a function call with arguments (`onclick = foo (True)`) of course executes the function.

That is... dirty, very dirty.

Just do :
```
def createFoo(a):
    def foo():
         print(a)

onlick=createFoo(true)
```

If you want something generic :
```
def createFoo(fct, **args):
    def handler():
         fct(**args) # not tested.

onlick=createCallback(foo, true, titi)
```

**Comment by PierreQuentel** [comment]
Thanks for the report @CyrilSLi and for the comments @denis-migdal 

In the commit above I have made a few changes related to this issue:
- passing a string as attribute `onclick` (`html.BUTTON("Foo", onclick="foo()")`) raises a `TypeError` saying that the value should be a callable, not a string. I don't remember why a string was allowed in previous version (and even less how it worked...) but it is clear that a function should be passed
- setting `element.onclick` removes the previous bindings
- setting it to a Javascript function allows a subsequent `unbind`

To pass values to a callback function, the standard way in Python is via a lambda, as in

```python
def foo(ev, x):
   print ("bar", x)

value = 99

document <= html.BUTTON("Foo", onclick=lambda ev,x=value:foo(ev, x))
```

**Comment by denis-migdal** [comment]
>     * setting `element.onclick` removes the previous bindings
Does it removes all bindings, even the ones explicitly added by `bind()` ? If it is the case, that'd be **_very_** dangerous.

In JS, "onclick" only removes the previous binding put with `onclick`, it doesn't remove the ones done with `addEventListener()`

In fact, it is not "really" a binding, but a member function that is called (if exists) when an event go through the object :
```javascript
class X extends HTMLElement {

    onclick = (ev) => {
         // TODO stuff
   }

}
```

**Comment by denis-migdal** [comment]
_**Details :**_

- What I said about `onclick` is true for all `onXXXX` in HTML/JS (as far as I know).


- You can implement `onXXXX` in two ways :
    1. If you want to stay close to JS : instead of using `bind()` you'd rather rely on the `onXXXX` property of the underlying `HTMLElement` (you could also decide to allow `unbind()` on it if not found in the binded event listeners).
    2. If you want `onXXXX` to be an "alias" of `bind()`, then `onXXX <=` should be used by default, and `onXXX = ` would unbind everything but be strongly disadvised ("you can do it, but don't do it").

In both ways, using `onclick = ` should be strongly discouraged in the documentation, though we could understand using it in the element construction. Using it outside is a safety hazard.

**Comment by PierreQuentel** [comment]
> In JS/HTML, "onclick" only removes the previous binding put with onclick, it doesn't remove the ones added with addEventListener()

Oh, I didn't know that. In the commit above I have removed the link between setting `onclick` and using `bind()`, this should solve the issue.

**Comment by denis-migdal** [comment]
Thanks, I will test it a little today to see if everything seems OK.


Also, I think I will soon update issue 2250, in hope to make your work easier :
- creating an issue for all requests regarding documentation changes, separating them so it doesn't pollute other issues.
- ordering "tasks/issues" by quickness (I think a few can be very very quick to do, and others are quite big).

Also to reassure you, I should be less active in issues creations in ~1 week, once my courses with my students over. xD

**Comment by denis-migdal** [comment]
I made some tests to understand a little more the `HTMLElement.onclick = ...` vs `HTMLElement.setAttribute('onclick', '...')`

So they are 2 distinct things :
- `HTMLElement.onclick` that is the function executed when the element is clicked ;
- the attribute `setAttribute('onclick')` that will **not be executed**, but when modified/set, **change the value** of `HTMLElement.onclick`. The inverse isn't true. Changes to `HTMLElement.onclick` doesn't change the `onclick` HTML attribute.

E.g. :
```javascript
elem.setAttribute('onclick', 'toto()') // update the HTML + HTMLElement.onclick
/* is doing something like that (cf below) when the attribute is modified :
str = elem.getAttribute('onclick');
elem.onclick = () => eval(str)
*/

elem.onclick = foo // don't change the value of the HTML Attribute 'onclick'. Meaning that :
elem.getAttribute('onclick') // is still equal to "toto()", but won't be called upon clicks.
```

Yeah the behavior is shitty (another reason to not use onclick xD).

**Comment by PierreQuentel** [comment]
The expectations in your test are not all correct I think:
- button `JS_to_Brython` has `onclick` set to `faa` in Brython, and `addEventListener('click', foo)` in JS code, so it's correct that it prints both "BRY FAA" and "JS FOO"
- there is a typo in the last JS test, `btn` should be `document.querySelector('#Brython_to_JS')`. WIth this change the result is "JS FAA" as expected

For the difference between `element.onclick` and `element.getAttribute("onclick")` there is an explanation of the difference between _attributes_ and _properties_ in the [documentation](https://www.brython.info/static_doc/3.12/fr/attributes.html). It's sometimes weird, I agree...

**Comment by denis-migdal** [comment]
> The expectations in your test are not all correct

The expectations were correct... the code weren't...
I'm an idiot... I put the wrong selector in the last test, and used `addEventListener` when I wanted to use `.onclick`.

So everything seems fine now. Sorry for that.
I really should sleep more (or drink more coffee) xD

However the issue for `onlick = window.foo` still exists ([more info](https://github.com/brython-dev/brython/issues/2254#issuecomment-1742406608))


````html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8"/>
        <title>X</title>
        <!-- Dependancies required to define custom Elements -->
        <!--<script type="text/javascript" src="/Brython-3.X/brython.js" defer></script>-->
        <!-- online version -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js">
        </script>
        <!-- issues with CORS... -->
        <script type="text/python">

            from browser import document;

            def foo(ev):
                print('    BRY FOO')
            def faa(ev):
                print('    BRY FAA')

            btn = document["Brython_listener"]
            btn.bind('click', foo)
            btn.onclick = faa

            btn = document["Brython_twice"]
            btn.onclick = foo
            btn.onclick = faa

            btn = document["DOM_to_brython"]
            btn.onclick = faa

            btn = document["JS_to_brython"]
            btn.onclick = faa

            btn = document["Brython_to_JS"]
            btn.onclick = foo
        </script>
    </head>
    <body>
        <button id="Brython_listener"></button>
        <button id="Brython_twice"></button>
        <button id="DOM_to_brython" onclick="foo()"></button>
        <button id="JS_to_brython"></button>
        <button id="Brython_to_JS"></button>
        <!-- HTML is STUPID : The defer attribute is ignored if the <script> tag has no src -->
        <script type="text/javascript">
            
            window.foo = () => console.log('    JS FOO');
            window.faa = () => console.log('    JS FAA');

            {
                let btn = document.querySelector('#Brython_listener');

                setTimeout(() => {
                    console.log('Brython_listener', 'expect  BRY_FOO+BRY_FAA');
                    btn.dispatchEvent( new Event('click') );
                }, 1000);
            }
            {
                let btn = document.querySelector('#Brython_twice');

                setTimeout(() => {
                    console.log('Brython_twice', 'expect  BRY_FAA');
                    btn.dispatchEvent( new Event('click') );
                }, 1000);
            }
            {
                let btn = document.querySelector('#DOM_to_brython');

                setTimeout(() => {
                    console.log('DOM_to_brython', 'expect BRY_FAA');
                    btn.dispatchEvent( new Event('click') );
                }, 1000);
            }
            {
                let btn = document.querySelector('#JS_to_brython');

                btn.onclick = foo;

                setTimeout(() => {
                    console.log('JS_to_brython', 'expect BRY_FAA');
                    btn.dispatchEvent( new Event('click') );
                }, 1000);
            }
            {
                let btn = document.querySelector('#Brython_to_JS');

                setTimeout(() => {
                    console.log('Brython_to_JS', 'expect JS_FAA');
                    btn.onclick = faa
                    btn.dispatchEvent( new Event('click') );
                }, 1000);
            }
        </script>
    </body>
</html>
````

**Comment by PierreQuentel** [comment]
I am closing the issue, if you think it should be reopened please comment again.
