### ISSUE TITLE
Incorrect behavior of sets: {''} | {0} gives {''} and discards 0

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#543]
Dear Brython developers,

Thanks for your awesome project. I started using your library to evaluate solutions on my introductory Python course https://snakify.org/ 

So far I spotted one bug of Python implementation:

![2017-01-08_03-22-51](https://cloud.githubusercontent.com/assets/1491908/21746332/0ce386c4-d552-11e6-9379-c695f5796c21.png)

```
Brython 3.3.0 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
>>> {''} | {0}
set({''})
```

Something like this is expected given you convert Python to JS, but is still annoying.

Could you please estimate if you could fix this any time soon? Alternatively, I may try to fix it on my own and upstream a patch to you afterwards. In this case, if you could spend a couple of minutes pointing to places of Brython source where the things are possibly going wrong and could be fixed, it could really speed up my investigation. So far I have limited understanding of your code base - I didn't have a chance to dig into.

Thanks you so much,
Vitaly

**Comment by vpavlenko** [comment]
I've just found another strange behavior of sets. Probably they are related:

![2017-01-08_03-43-09](https://cloud.githubusercontent.com/assets/1491908/21746394/ac732940-d554-11e6-8dfc-d2841c5bd4e7.png)

```
Brython 3.3.0 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
>>> a = set(range(20))
print(a)
a.intersection_update({5})
print(a)
set({0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19})
set({5, 10, 11, 12, 13, 14, 15, 16})
```

**Comment by PierreQuentel** [comment]
здравствуй Виталий,

сначала, поздравляю за snakify.org, мне очень ндравнтся ! (sorry for the mistakes, I'm just learning...)

The commits referenced above should fix the second bug you reported. For the first one I'm not sure : I get the correct result with Firefox on Windows XP but could reproduce the bug with a Safari simulator. Can you test again with the latest version on the repository ?

**Comment by vpavlenko** [comment]
Bonsoir Pierre !

Great to hear you're learning Russian. And thank you for such a quick response.

So, I tested the new brython.js file on Chrome 55.0.2883.95 on my Mac, and the behavior is the same as you get with Safari: the second bug is now gone, the first still persists. Could I somehow help with investigating it?

**Comment by PierreQuentel** [comment]
The problem is most probably in the implementation of `set.add` in the script [py_set.js](https://github.com/brython-dev/brython/blob/master/www/src/py_set.js#L280). The Javascript implementation probably compares `""`  and `0`  as equal. If you can fix this it would be great !

**Comment by PierreQuentel** [comment]
While working on another topic I realized that this bug was also present with Chrome on my PC (I usually use Firefox for development). I found that it was related to the fact that `[''].indexOf(0)` is -1 for Firefox, but 0 for Chrome...

The commit referenced above should fix the bug. Is it the case for you ?

**Comment by vpavlenko** [comment]
@PierreQuentel Thank you so much, your fix works for us.
